language: python

python:
  - "3.5"

services: postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE="kpi_core.settings"
    - PYTHONPATH="/home/travis/build/austyns/kpi_core_tr"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO=2.2 DB=postgresql

#commands to install dependencies
install:
  - pip install -q Django==$DJANGO
  - pip install -q -r requirements.txt

before_script:
  - psql -c 'create database test_db;' -U postgres

#command to run the test suite
script:
  - python manage.py test