# Generated by Django 2.2.1 on 2019-05-29 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measurable_param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.TextField(max_length=300)),
                ('question_slug', models.SlugField(blank=True, max_length=400)),
                ('question_reg_at', models.DateTimeField(auto_now_add=True)),
                ('question_weight', models.CharField(blank=True, max_length=20)),
                ('question_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Department')),
            ],
        ),
        migrations.CreateModel(
            name='System_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('ad_name', models.CharField(max_length=128, unique=True)),
                ('ad_email', models.CharField(max_length=128, unique=True)),
                ('ad_password', models.CharField(max_length=256)),
                ('ad_slug', models.SlugField(blank=True, unique=True)),
                ('ad_phone', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('lga', models.CharField(blank=True, max_length=128)),
                ('ad_status', models.CharField(blank=True, max_length=15)),
                ('ad_role', models.CharField(blank=True, max_length=15)),
                ('ad_reg_at', models.DateTimeField(auto_now_add=True)),
                ('ad_reg_by', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128)),
                ('fullname', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_title', models.TextField(max_length=300)),
                ('option_weight', models.CharField(blank=True, max_length=20)),
                ('option_value', models.IntegerField(blank=True, default=0, null=True)),
                ('option_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.Measurable_param')),
            ],
        ),
        migrations.CreateModel(
            name='Form_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.TextField(blank=True, max_length=256)),
                ('score', models.CharField(blank=True, max_length=128)),
                ('week', models.CharField(blank=True, max_length=128)),
                ('form_registered_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Measurable_param')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Staff')),
            ],
        ),
    ]
